language: node_js
node_js:
- '0.10'
script: ./deploy.sh
notifications:
  email:
    recipients:
      - david@dmarby.se
    on_success: change
    on_failure: always
env:
  global:
    secure: sGwKDDqZ1w+SJgIFwbFLwVqKsEr3qCQ5jmsRRQQKn58+XSVBg+Y2c5rrXCXbztMW/Qal2tmrm6pIEh/iXnNWLX9+8XbnhO20UTDJKNyvgrF8+O4NaXZVHGybGMUBuE531cKfKS62rSdfl/4CXsZ1lk/P6VpOdWNE9jL6BMxl7Dc=
